name: 'deploy when push'

on:
  push:
    branches: [develop]
  pull_request:
    branches: [develop]

jobs:
  build:
    name: deploy to staging
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source code.
        uses: actions/checkout@v3

      - name: executing remote ssh commands using password
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          password: ${{ secrets.SERVER_PASSWORD }}
          port: ${{ secrets.SERVER_PORT }}
          script: |
            cd ~/web37-ZelloDraw/ && git pull origin develop
            cd ~/web37-ZelloDraw/frontend/
            npm i
            npm run build
            cd ~/web37-ZelloDraw/backend/
            npm i
            npm run deploy:prod
